#ifndef __INCLUDE_GUARD__UNIT_TEST_FUNCTION_ARG_HELPERS_H__
#define __INCLUDE_GUARD__UNIT_TEST_FUNCTION_ARG_HELPERS_H__

#include <stdint.h>

uint8_t TEST__is_valid_hex_string();

#endif // __INCLUDE_GUARD__UNIT_TEST_FUNCTION_ARG_HELPERS_H__