name: ESP32 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up ESP-IDF
      uses: espressif/esp-idf-action@v1.3
      with:
        version: 'latest'
        
    - name: Configure ESP-IDF
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        idf.py set-target esp32c3  # Replace with your target if different

    - name: Build ESP32 Project
      run: idf.py build

    - name: Check for Build Errors
      if: failure()
      run: echo "Build failed with errors."
